
paginate: 10 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
encoding: utf-8
markdown: kramdown  #use kramdown to parse markdown
permalink: /:categories/:title.html

name: 卓文理

author:
  name: 卓文理
  email: 531840344@qq.com
  github: zhuowenli
  twitter: vnnlee zhuo
  bio: 我在这里，高清有码！
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml

categories:
  frontend: 前端开发
  design: 设计网摘